export const SET_PRODUCTS = "SET_PRODUCTS";
export const SELECTED_PRODUCT = "SELECTED_PRODUCT";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADJUST_ITEM_QTY = "ADJUST_ITEM_QTY";
export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";
